added model: Bet and Gain, added controller: ConsoleHandler, added da…
Fedich09/jv-create-annotation pull request #1
Opened 2021-01-06 11:58 UTC by Fedich09

…o: BetDao, GainDao and implementation for them: BetDaoImp and GainDaoImpl, added db: Storage and Maib class

2021-01-06 12:06 UTC, sanek98cv approved these changes

2021-01-08 12:58 UTC, dmytro-hryhoruk requested changes

2021-01-08 12:58 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImp();
access modifier

2021-01-08 12:58 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImp();
other Dao?

2021-01-08 12:58 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
Try to enter only one word

2021-01-08 14:46 UTC, dmytro-hryhoruk requested changes

2021-01-08 14:46 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
So what will happen if you will enter only one world?

2021-01-08 14:46 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +            betDao.add(bet);
Let's add gain and bet only if there are not null

2021-01-08 14:46 UTC, dmytro-hryhoruk commented on src/main/java/core/controller/ConsoleHandler.java
> +                    + (gain == null ? null : gain.toString()));
these checks and calling toString() is done automatically by System.out.println (check it)

2021-01-08 18:20 UTC, dmytro-hryhoruk approved these changes

2021-01-10 13:44 UTC, merged